/*
 * MIT License
 * Copyright (c) 2024-2025 Robert Vokac
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "PageShell.h"
#include <sstream>

std::string pageShellOpen(const std::string& basePrefix, const std::string& title) {
    std::ostringstream out;
    out << R"(<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href=")" << basePrefix << R"(favicon.ico" sizes="16x16">
<link rel="stylesheet" href=")" << basePrefix << R"(assets/style.css">
<script src=")" << basePrefix << R"(assets/app.js" defer></script>
<title>)" << title << R"(</title>
<!-- Generated by: https://code.openeggbert.org/openeggbert/youtubedl-frontend -->
</head>
<body>
<header class="site-header"><div class="inner">
<a class="brand" href=")" << basePrefix << R"(videos.html"><span class="dot"></span>Youtube archive</a>
<nav class="header-nav">
<a href=")" << basePrefix << R"(stats.html">Stats</a>
<select id="theme-select" class="theme-select" aria-label="Theme">
<option value="auto" selected>Auto</option>
<option value="light">Light</option>
<option value="dark">Dark</option>
</select>
</nav>
</div></header>
<main class="page">
)";
    return out.str();
}
